// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/zoomacode/homedash/internal/state"
	"sort"
	"strconv"
	"strings"
	"time"
)

func Sensors(snap state.Snapshot) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"sensors\" hx-get=\"/fragment/sensors\" hx-trigger=\"sse:sensors\" hx-swap=\"outerHTML\"><h2>Sensors</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(snap.Sensors) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"empty\">no sensor readings yet</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		for _, group := range groupNames(snap) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"group\"><h3>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(group)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/sensors.templ`, Line: 22, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</h3><div class=\"tiles\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, sensor := range groupSensors(snap, group) {
				var templ_7745c5c3_Var3 = []any{"tile", levelClass(sensor), templ.KV("stale", isStale(sensor))}
				templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var3...)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var3).String())
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/sensors.templ`, Line: 1, Col: 0}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"><div class=\"name\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(sensor.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/sensors.templ`, Line: 26, Col: 38}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div><div class=\"value\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(formatValue(sensor))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/sensors.templ`, Line: 28, Col: 29}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if sensor.Unit != "" {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<span class=\"unit\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var7 string
					templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(sensor.Unit)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/sensors.templ`, Line: 30, Col: 41}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if isStale(sensor) {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<span class=\"stale-badge\">stale</span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func groupNames(s state.Snapshot) []string {
	seen := map[string]bool{}
	var out []string
	for _, sn := range s.Sensors {
		if !seen[sn.Group] {
			seen[sn.Group] = true
			out = append(out, sn.Group)
		}
	}
	sort.Strings(out)
	return out
}

func groupSensors(s state.Snapshot, group string) []state.Sensor {
	var out []state.Sensor
	for _, sn := range s.Sensors {
		if sn.Group == group {
			out = append(out, sn)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Order < out[j].Order })
	return out
}

func formatValue(s state.Sensor) string {
	f, err := strconv.ParseFloat(s.Value, 64)
	if err != nil {
		return s.Value
	}
	return strconv.FormatFloat(f, 'f', s.Decimals, 64)
}

// levelClass returns a CSS class name based on the sensor's name and value:
//
//	level-good (green) / level-ok (yellow) / level-warn (orange) / level-bad (red)
//
// Empty string means no color band.
func levelClass(s state.Sensor) string {
	f, err := strconv.ParseFloat(s.Value, 64)
	if err != nil {
		return ""
	}
	switch strings.ToLower(s.Name) {
	case "temperature":
		return TempLevelClass(f)
	case "air quality":
		// US AQI scale (lower is better).
		switch {
		case f <= 50:
			return "level-good"
		case f <= 100:
			return "level-ok"
		case f <= 150:
			return "level-warn"
		default:
			return "level-bad"
		}
	case "humidity":
		// Indoor comfort: 30-60% ideal; 20-30 or 60-70 ok; outside that warn.
		switch {
		case f >= 30 && f <= 60:
			return "level-good"
		case f >= 20 && f <= 70:
			return "level-ok"
		case f >= 15 && f <= 75:
			return "level-warn"
		default:
			return "level-bad"
		}
	case "pressure":
		// Sea-level normal ~1013 hPa. Tight band = normal, wider = caution.
		switch {
		case f >= 1005 && f <= 1025:
			return "level-good"
		case f >= 995 && f <= 1035:
			return "level-ok"
		default:
			return "level-warn"
		}
	}
	return ""
}

// TempLevelClass returns a temperature-band CSS class. Bands are tuned for
// indoor + outdoor air in degrees Celsius and reused by the weather widget
// so the dashboard's two thermometers stay color-consistent.
func TempLevelClass(c float64) string {
	switch {
	case c < 10:
		return "level-cold"
	case c < 15:
		return "level-chill"
	case c < 20:
		return "level-cool"
	case c < 24:
		return "level-perfect"
	case c < 28:
		return "level-warmish"
	case c < 35:
		return "level-hot"
	default:
		return "level-boiling"
	}
}

func isStale(s state.Sensor) bool {
	if s.StaleAfter == 0 {
		return false
	}
	return time.Since(s.UpdatedAt) > s.StaleAfter
}

var _ = templruntime.GeneratedTemplate
